# Generated by Django 4.1 on 2024-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlusEV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sport", models.CharField(max_length=20)),
                ("market", models.CharField(max_length=40)),
                ("date", models.DateTimeField()),
                ("event", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("outcome", models.CharField(max_length=10)),
                ("point", models.FloatField()),
                ("betmgm_ev", models.FloatField()),
                ("draftkings_ev", models.FloatField()),
                ("fanduel_ev", models.FloatField()),
                ("betrivers_ev", models.FloatField()),
                ("bovada_ev", models.FloatField()),
                ("pinnacle_ev", models.FloatField()),
                ("average_ev", models.FloatField()),
                ("betmgm_odds", models.FloatField()),
                ("draftkings_odds", models.FloatField()),
                ("fanduel_odds", models.FloatField()),
                ("betrivers_odds", models.FloatField()),
                ("bovada_odds", models.FloatField()),
                ("pinnacle_odds", models.FloatField()),
                ("average_odds", models.FloatField()),
            ],
        ),
    ]
