# Generated by Django 4.1 on 2024-04-10 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pev_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plusev",
            name="pair_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
