# Generated by Django 4.1 on 2024-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pev_app", "0002_plusev_pair_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plusev",
            name="win_prob",
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
