# Generated by Django 4.1 on 2024-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pev_app", "0003_plusev_win_prob"),
    ]

    operations = [
        migrations.AddField(
            model_name="plusev",
            name="betparx_ev",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="betparx_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="espnbet_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="espnbet_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="hardrockbet_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="hardrockbet_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="superbook_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="superbook_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="tipico_us_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="tipico_us_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="williamhill_us_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="williamhill_us_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="windcreek_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plusev",
            name="windcreek_odds",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
