# Generated by Django 4.1 on 2024-04-15 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pev_app", "0004_plusev_betparx_ev_plusev_betparx_odds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plusev",
            name="betparx_ev",
        ),
    ]
