# Generated by Django 4.1 on 2024-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pev_app", "0005_remove_plusev_betparx_ev"),
    ]

    operations = [
        migrations.AddField(
            model_name="plusev",
            name="betparx_ev",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
