# Generated by Django 4.1 on 2024-04-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pev_app", "0007_alter_plusev_average_ev_alter_plusev_betmgm_ev_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacedBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet_amount", models.FloatField()),
                ("placed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "plus_ev",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pev_app.plusev"
                    ),
                ),
            ],
        ),
    ]
