# Generated by Django 4.1 on 2024-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pev_app", "0008_placedbet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plusev",
            name="outcome",
            field=models.CharField(max_length=100),
        ),
    ]
